import { Article } from './article';
 
export const ARTICLES: Article[] = [
	{
		id: 11,
		title: 'POSTCARDS FROM IRAN',
		country: 'Iran',
		content: 'Apa yang terlintas di pikiran kalian ketika mendengar kata IRAN? Negara perang? Konflik politik? Negara timur tengah? Negara perang? Sejujurnya ga pernah terlintas dalam pikiran gue, atau bahkan punya motivasi untuk pergi dan melihat Iran, sampe suatu hari liat postingan tentang Iran di instagram nya Trinity(Naked Traveler), dan hal pertama yang muncul di kepala gue adalah “Wow, look at that majestic patterns on the wall, so awesome”. Tapi layaknya orang biasa yang ga pernah denger tentang Iran, gue juga dulunya berpikir “Kayaknya hal yang gila kalo gue ke Iran, secara itu negara yang terletak jauh di Timur Tengah, dan termasuk negara yang punya konflik politik dengan Amerika, not safe bruhh”.Singkat cerita, entah kesamber apa gue beli aja tiket ke Iran (tiket promo Airasia). I know.. Impulsive, right? Nah, dari sana lah gue mulai cari tau tentang Iran. Dan so far sejauh research gue di internet, banyak orang bilang bahwa orang Iran itu super ramah, perhatian dan baik. Okay, that’s a good start for a solo traveler like me! Tapi emang pada dasarnya gue gampang parno, meskipun udah banyak info yang baik baik tentang Iran, tetep aja H-1 sebelum berangkat, perut gue mules ngebayanganin seandainya gue jadi tawanan perang di Iran (I know super exegerating, but its me lol), sampai questioning myself whether gue harus pergi atau simply just cancel the whole trip. Tapi cupu banget kalo ampe nyerah sebelum beneran pergi ke medan perang, jadi yaudah dengan berbekal tekad kuat dan doa, gue berangkat ke Iran..Selama 2 minggu disana, gue mengunjungi beberapa kota yang emang cukup mainstream sih, semacam “cities you gotta explore for the first timer” gitu. Gue memulai trip ini dari Tehran, ibukota Iran lalu ke kota gurun bernama Yazd dan Meybod, lanjut ke Esfahan, dan terakhir ke kota cinta dan seni yaitu Shiraz. I loved it beyond anything I expected. Sekarang kalo ditanya orang  best country I’ve visited so far, gue pasti jawab Iran. Parah! Gue gatau harus gimana jelasinnya, karena emang banyak banget hal yang bikin gue surprise terhadap negara yang satu ini, dari arsitekturnya yang berumur ribuan tahun, rasa kebabnya yang super otentik, atmosfir kotanya yang mirip Eastern Europe (serius, semirip itu), serunya masuk keluar Grand Bazaar, souvenir yang super pengen dibeli semuanya, dan yang paling berkesan adalah orangnya, terbaik :”).  Untuk cerita cerita seru selama perjalan',
		createdAt: '8/6/2017'
	}
];